# Generated by Django 5.2.7 on 2026-01-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.CharField(max_length=250)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
